#!/usr/bin/perl
use strict;
use warnings;

## Author: Qiang Gong <qgong@coh.org>

## Get protein-changing mutations (non-silent) from VCF files generated by VarScan 2
## and annotated by ANNOVAR program.
## Tested versions: VCFv4.1; VarScan v2.3.6; ANNOVAR 2015-06-17

my $file = shift or die("Usage: $0 <*.vcf>\n");

open IN, $file or die($!);
while (<IN>) {
    chomp;
    if (/^##/) {
        print "$_\n";
        next;
    }
    if (/^#/) {
        print "##FILTER=<ID=silent,Description=\"Mutations that would not change proteins\">\n";
        print "$_\n";
        next;
    }
    my @a    = split /\t/;
    my $info = $a[7];
    if ( $info =~ /Func.refGene=splicing/ ) {
        print join "\t", @a;
        print "\n";
        next;
    }
    next
      if $info =~ /ExonicFunc.refGene=\./
          || $info =~ /ExonicFunc.refGene=synonymous_SNV/
          || $info =~ /ExonicFunc.refGene=unknown/;
    print join "\t", @a;
    print "\n";
}
close IN;

